{% set name = "cucumber-tag-expressions" %}
{% set version = "6.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ec6bcf0957d8c6ea7b817d282b4e04243c0de087dda1e354505a5544937a574e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - invoke
    - python >=3.6

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cucumber/tag-expressions
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
